config/routes.rb
MerjerzHtml::Application.routes.draw do

  match '/home', :to => 'pages#home' #new added by pnina
  match '/write', :to => 'pages#write'#new added by pnina
  match '/how_it_works', :to => 'pages#how_it_works' #new added by pnina
  match '/contact', :to => 'pages#contact'
  match '/terms_of_service', :to => 'pages#terms_of_service'
  match '/about', :to => 'pages#about'
  match '/faq', :to => 'pages#faq'
  match '/help', :to => 'pages#help'
  match '/learning_center', :to => 'pages#learning_center' #new added by pnina
  match '/signout', :to => 'sessions#destroy'
  match '/callback', :to => 'linked_in_connections#create'
  match '/mycorporations', :to => 'corporations#index'
  match '/mydeals', :to => 'deals#index'
  match '/search', :to => 'search#index'

  root :to => 'pages#home'

  resources :users
  resources :profiles
  resources :comments
  resources :likes

  resources :corporations do
    resources :reviews
    member do
      post 'rate'
    end
  end

  resources :deals do
    resources :reviews
    member do
      post 'rate'
    end
  end

  resources :reviews do
    resources :comments
    resources :likes
  end

  resources :relationships
  resources :sessions, :only => [:new, :create, :destroy]
  resources :linked_in_connections, :only => [:new, :create, :destroy]

end

  

app/models/deal.rb
class Deal < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/corporations_controller.rb
class CorporationsController < ApplicationController
  def index
    
  end
  
  def show
    
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def deals
  end  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def title
    base_title = "Merjerz"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end

  def logo
    image_tag("merjerz_logo.jpg", :alt => "Merjerz")
  end
   # new added images section
  def home
    image_tag("home.png", :alt => "Home")
  end
   def raiting_triangle_img
      image_tag("raiting_triangle.png", :alt => "More", :class =>"more_raitings", :size => "10x7" )
   end 
  def like_img
     image_tag("smiley_happy.png", :alt => "Like", :size => "19x19")
  end
  def dislike_img
    image_tag("smiley_sad.png", :alt => "Like", :size => "19x19")
  end
  def responses_img
    image_tag("responses.png", :alt => "Responses", :size => "24x19")
  end
  
  def avatar_img
     image_tag("avatar.png", :alt => "Responses", :size => "67x67")
  end
  
  def deal_img
     image_tag("deal_icon_green.png", :alt => "", :size => "65x65")
  
  end
  
  def corporation_img
    image_tag("corporation_icon_green.png", :alt => "", :size => "65x65")
   
  end
  def should_buy_img
     image_tag("should_buy.png", :alt => "", :size => "58x44")
  end

  def compute_average_rating(entity)
    dimensions = case
                   when entity.class==Corporation
                     %w{integrity innovation technology product_quality service_levels}
                   when entity.class==Deal
                     [:revenue_synergies, :cost_synergies, :culture_match, :team_enhancement, :brand_enhancement, :product_enhancement, :geography_enhancement]
                 end
    sum = dimensions.inject(0) do
    |result, element|
      result + entity.rate_average(false, element)
    end
    sum / dimensions.length
  end


  def display_average_rating(entity)
    "Average rating:  #{compute_average_rating(entity).round(1).to_s} /5"
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/corporations_helper.rb
module CorporationsHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/comments/_comment_no_response.html.erb
<div class="article_responses hidden">
		<div class="triangle_responses"></div>
		<h2>Responses</h2><span class="plus">+ </span><a class="add_response_link">Add Response</a>
		<div class="add_response">
			<h1 class="left">Add Response</h1><a class="close left initial_response">x</a>
			<%= form_tag  do %>
			<%= text_area_tag :nil %>	
			 <%= submit_tag :Add, :class=>"response_butt" %>		
			<a class="cancel_link initial_response">Cancel</a>
			<% end %>	
		</div>
	
</div>

app/views/comments/_list_comments_for_commentable.html.erb
<div class="article_responses hidden">
		<div class="triangle_responses"></div>
		<h2>Responses</h2><span class="plus">+ </span><a class="add_response_link">Add Response</a>
		<div class="add_response hidden ">
			<h1 class="left">Add Response</h1><a class="close left">x</a>
			<%= form_tag  do %>
				<%= text_area_tag :nil %>	
				 <%= submit_tag :Add, :class=>"response_butt" %>		
				<a class="cancel_link">Cancel</a>
			<% end %>	
		</div>
		<div class="responses_body">
			<div class="responses_avatar">
				<img src="../assets/avatar.png" height="67" width="67">
				<div class="member_name">Vadim Zeladorski</div>
			</div>
			<p>response text goes here bbbbbbbbbbb sit amet, mus odio enim orci, turpis purus pede donec. A nulla consequat proin quis, auctor purus urna eros urna, sed quis sociosqu eu auctor. Volutpat ornare in mi, nec in velit </p>	<time>24/11/11</time>
		    <div style="clear: both;">	</div>
		</div>
</div>

app/views/corporations/_corporation.html.erb
<td>
	<div class="corporations">
		<div class="corporation_logo"></div>
		<div class="corporation_header">company name</div>
		<div class="ratings_corp"></div>
		<div class="insights">Reviews(12)</div>	
	</div>
</td>

app/views/corporations/_form.html.erb
<label class="inner_header top">Corporation name</label><input type=text class="new_corp">
									<label class="inner_header">Title</label>
									<input type=text class="new_corp">
									<label class="inner_header">Description</label>
									<textarea id="new_deal_general"></textarea>
									<label class="inner_header">Ratings</label>
									<div id="raitings_new">
										<ul>
											<li><label>Innovation:</label>raitings go here</li>
											<li><label>Integrity:</label>raitings go here</li>
											<li><label>Technology:</label>raitings go here</li>
											<li><label>Product quality:</label>raitings go here</li>
											<li><label>Service levels:</label>raitings go here</li>
										</ul>								
									</div>
									
									<div id="relationship">
										<label class="inner_header">Relationship</label>
										<div>Describe your relationship to this corporation</div>
										<input id="Investor" type="checkbox"  class="checkbox" name="option1" value="Investor"><label class="checkbox" for="Investor">Investor</label>
										<input id="Customer" type="checkbox" name="option2" value="Customer"><label class="checkbox" for="Customer">Customer</label>
										<input id="Partner" type="checkbox" name="option3" value="Partner"><label class="checkbox" for="Partner">Partner</label>
										<input id="Supplier" type="checkbox" name="option4" value="Supplier"><label class="checkbox" for="Supplier">Supplier</label>
										<input id="Employee" type="checkbox" name="option5" value="Employee"><label class="checkbox" for="Employee">Employee</label>
										<input id="Ex employee" type="checkbox" name="option6" value="Ex employee"><label class="checkbox" for="Ex employee">Ex employee</label>
										<input id="other" type="checkbox" name="option6" value="other"><label class="checkbox" for="other">other</label>
									</div>	
									
									<footer><input type="button" value="Add Review" class="green_back submit"></footer>
								</section>

app/views/corporations/_show_content_in_tabs.html.erb
<!-- **************************TABS***************************************************** -->					

	<div id="tabs" class="deal_page">
		<div class="add_container"><a title="Add Insights to this deal" class="gray_back add_butt">Add Insight</a></div>
				 <ul>
					<li><a href="#tabs-1">Reviews</a></li>
					<li><a href="#tabs-2">Deals</a></li>
					<li><a href="#tabs-3">Info</a></li>									
				</ul>
		 <div id="tabs-1" class="tabs_container"> 
		 	<%=render :partial=> "reviews/review", :locals=>{:responses_text=>"2 Response",:responses_type=>"yes_responses"}%> <!-- show review content-->
		 	<!--   ************************************* paiging ****************************************************    -->
			<%=render :partial=> "layouts/paiging" %>
		</div>	
		 <div id="tabs-2" class="tabs_container secondary_tab "><!--show deals -->
		 	<article class="tabs_display">
				 <section class="deals_filter"">
						<table>
							<tr>
								<%=render :partial=> "deals/deal" %>
								<%=render :partial=> "deals/deal" %>
							</tr>								
						</table>
				 </section>
		   </article>		 	
		 </div>
		 <div id="tabs-3" class="tabs_container secondary_tab">
		 	<article class="tabs_display corp_info">
				<h1>Corporation  title</h1>
				<p>Corporation  info</p>								  			
			</article>
		 </div>
  </div>		 			


							
							

app/views/corporations/index.html.erb
						<div id="intro"></div>	<!--fix rails bug -->
						<!-- ************************** SEARCH + INNER HEADER***************************************************** -->	    		
						<div id="inner_header_big" class="light_gray_back">
							<h1 id="top_header">Corporations</h1>
							   <%=render :partial=> "search/form" , :locals => { :header_name => 'text_inner' } %>					
							<div id="add_top" class="add_corporation">
								<div class="circle left gray_back">+</div>
									<a  href="#">Add Corporation Review</a>									
							</div>
						</div>
						<div id="main_home" class="corp_nav">
						<!-- ******************************** BREAD CRUMBS **********************************************-->
						<div class="bread_crumbs"><a href="">Home</a> >Corporations</div>
						<!-- **************************CORPORATIONS FILTERS***************************************************** -->				
							<section class="corp_filter">
									<div class="level2_body"><div class="level2_header deals_fillter">Top Rated</div></div>	
									<table>
										<tr>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
										</tr>										
									</table>
								</section>
								<section class="corp_filter">		
									<div class="level2_body"><div class="level2_header deals_fillter">Most Viewed</div></div>
									<table>
										<tr>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
										</tr>											
									</table>																
							     </section>
							     <section class="last_filter corp_filter">		
									<div class="level2_body"><div class="level2_header deals_fillter">Recently Added</div></div>
									<table>
										<tr>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
											<%=render :partial=> "corporations/corporation" %>
										</tr>										
									</table>																
							     </section>
							     <!-- ************************* ADD CORPORATION *********************************** -->
							     <section id="add_link">
									<div id="add_top" class="add_corporation">
										<div class="circle left gray_back">+</div>
										<a  href="#" class="add_deal">Add Corporation Review</a>									
									</div>
								</section>
						</div><!-- main home-->	

	<script>

</script>											

app/views/corporations/new.html.erb
<div id="intro"></div>	<!--fix rails bug -->
<!-- ************************** header ***************************************************** -->
						<div id="inner_header" class="light_gray_back">
					
							<h1 id="top_header">New Corporate Review</h1>
						</div>	
								
					<div id="main_home">
						<!-- ******************************** BREAD CRUMBS **********************************************-->
						<div class="bread_crumbs bc_padding"><a href="">Home</a> > <a href="">Deals</a> > New Corporate Review</div>
						
						<!-- ******************************************************************************* -->	
						<section id="newpage_wrapper">
							<div class="level2_body"><div class="level2_header add_corporate_filter">Add New Corporate Review</div></div>
								<section id="add_new" class="bottom_padding">						
									<%=render :partial=>'form'%> <!--form fields  -->
						</section>		
						<!-- ************************************** EXPLANATION ABOUT FORM FILLING ************************************* -->		
							
							<aside class="new_page"> 
							<a class="dialog_but" href="#">Which content is important in a Corporation Review?  </a>
							<div class="dialog_content">Corporation Reviews are very broad as they can relate to any and all aspects of a corporation. If you have some knowledge, experience or understanding – share it. It does not have to be unique, and of course it must not involve a breach of confidentiality or privacy, or involve defamatory statements. Some core areas of interest are: integrity (are the people and culture honest and ethical), innovation (are they inventive, creative), technology, product quality, and service levels. There is much, much more to say, and whatever is relevant is appropriate for Corporation Review.  
Refer to our guidelines below on confidentiality and privacy issues, and whistle-blowing. </div>
							<a class="dialog_but" href="#">How to write an effective Corporation Review:</a>
							<div class="dialog_content">
								<p class="double_box">
									An effective Corporation Review is <b>specific, clear</b>, and <b>factual</b></b>. 
To be <b>specific</b>, give details of what you’re describing, don’t leave it at generalities. Instead of “their product is innovative”, write “their flagship product is 40% faster than their main competitor’s due to their new proprietary algorithm.” To be <b>clear</b>, say exactly what you mean, don’t just hint. Instead of “this company is a loser,” try “they’re raising prices 5%, again, even while losing customers (down 10% against last year) and their marketing cost keeps going up.” Finally, be <b>factual</b>. If you write “they’re losing their technological edge” support it with facts, such as: “their flagship patents have only a couple of years to run, they have nothing new in the pipeline; they need to acquire some talent quickly or join the scrapheap of has-been companies.” 
Corporation Reviews that are specific, clear and factual will have the greatest impact.
								</p>
							</div>
							<a class="dialog_but" href="#">How long should a Corporation Review be?</a>
							<div class="dialog_content">Like a good skirt - short enough to be interesting, long enough to cover the essentials. Seriously, get your point across succinctly, but don’t be so brief that no one can understand your message. If you have many useful points to make, by all means make them all. On the other hand, if you make your point there’s no need to repeat it. </div>
							<a class="dialog_but" href="#">Language</a>
							<div class="dialog_content">Merjerz is English-language only. That is the global hi-tech language and we’re keeping it that way</div>
							<a class="dialog_but" href="#">Confidentiality & Privacy</a>
							<div class="dialog_content">Don’t breach it. Even if you’re writing anonymously, posting a corporation or person’s confidential or private information could be a crime and a tort. In other words, it is wrong and you could get into lots of trouble. You could do damage to people and corporations and may be sued for that. What’s more, the value of an M&A deal hardly ever depends on confidential information. In other words: revealing confidential information is not going to materially change the prospect of a deal. If you think you have some astonishing whistleblowing information, take it to the legal authorities. Otherwise, keep your contribution within the realms of relevant, non-confidential business and technology insights and opinion.</div>
							<a class="dialog_but" href="#">Comments about people</a>
							<div class="dialog_content">There’s generally no need to comment about individuals. Corporations worth commenting about are always bigger than one person. Comments about the quality of management, the culture, the norms and processes, the faith management have in the team, the HR policies and mindset are all fair game. They’re all relevant to other businesses, and don’t depend on one person. Same goes for culture, performance, service, innovation, technology, growth, prospects etc. There’s no need to single out people, even if you don’t name them. Doing so may entail defamation, for which you may be sued, and can be very harmful even to other people. If you know of someone who has broken the law, tell the authorities. </div>
							<a class="dialog_but" href="#">Anonymous or Real name?</a>
							<div class="dialog_content">Using your real name will greatly increase the credibility of your insights and comments. In general, you should be writing under your real name. However, sometimes you really can’t use your name. You may be conflicted between people you like and companies you dislike, or in some other way. If you can’t post under your true name, post anonymously, but remember that readers will then give your comments less weight. </div>
			</aside>
				<div style="clear: both;">	</div>				
	</div><!-- main home-->

app/views/corporations/show.html.erb
	<div id="intro"></div>	<!--fix rails bug -->
	<!-- ************************** SEARCH ***************************************************** -->
	<div id="inner_header_big" class="light_gray_back">
		<h1 id="top_header">Corporations</h1>
		 <%=render :partial=> "search/form" , :locals => { :header_name => 'text_inner' } %>										
		 <div id="add_top" class="add_corporation">
				<div class="circle left gray_back">+</div>
					<a  href="#">Add Corporation Review</a>									
				</div>
		 </div>					
		<div id="main_home" class="corp_nav">
		<!-- ******************************** BREAD CRUMBS **********************************************-->
		<div class="bread_crumbs"><a href="">Home</a> > <a href="#">Deals</a> > company A should buy Company B</div>
		<!-- **************************DEAL HEADER***************************************************** -->				
		<section id="deal_header">
			<div class="comp">company A container</div>						
			<div style="clear: both;">	</div>	
			<div class="review_box"><h1 class="left">Company A Review</h1><div class="ratings_inner"></div></div>
		</section>	
		<div style="clear: both;">	</div>
		<!-- **************************TABS***************************************************** -->					
		<section id="deal_tabs">
			 <%=render :partial=> "show_content_in_tabs" %>					
		</section>
		<!-- ************************************* competing deals ******************************************* -->
		<section  class="corp_filter bottom_padding">
			<div class="level2_body"><h1>other Corporations that may interest you</h1></div>	
				<table>
					 <tr>
						<%=render :partial=> "corporations/corporation" %>
						<%=render :partial=> "corporations/corporation" %>
						<%=render :partial=> "corporations/corporation" %>
						<%=render :partial=> "corporations/corporation" %>					
					 </tr>										
				</table>				
		</section>
							
						

app/views/deals/_deal.html.erb
<td>
	<div class="deals">
		<div class="comp corp_up">Corporation A</div>
		<div class="comp corp_down">Corporation B </div>													
	</div>
	<div class="deal_header">company A should buy company B</div>
	<div class="ratings_deals"></div><div class="insights">Insights(12)</div>
</td>

app/views/deals/_form.html.erb
<%= form_tag  do %>
					<section id="buy_comps">
							<div class="select_comp">
									<label class="inner_header">Corporation name</label>
									<input type=text>
							</div>
											<div class="left">
												<%=should_buy_img%><br>
												<span>Should buy</span>									
											</div>
											<div>
												<label class="inner_header">Corporation name</label>
												<input type=text>
											</div>
						</section>
										<label class="inner_header">Description</label>
										<textarea id="new_deal_general"></textarea>
										<label class="inner_header">Ratings</label>
										<div id="raitings_new">
											<ul>
												<li><label>Innovation:</label><div class="ratings_inner"></div></li>
												<li><label>Integrity:</label><div class="ratings_inner"></div></li>
												<li><label>Technology:</label><div class="ratings_inner"></div></li>
												<li><label>Product quality:</label><div class="ratings_inner"></div></li>
												<li><label>Service levels:</label><div class="ratings_inner"></div></li>
											</ul>		
										</div>
										<div id="relationship">
											<label class="inner_header">Relationship</label>
											<div>Describe your relationship to the target corporation</div>
											<input id="t_Investor" type="checkbox" name="option1" value="Investor"><label class="checkbox" for="t_Investor">Investor</label>
											<input id="t_Customer" type="checkbox" name="option2" value="Customer"><label class="checkbox" for="t_Customer">Customer</label>
											<input id="t_Partner" type="checkbox" name="option3" value="Partner"><label class="checkbox" for="t_Partner">Partner</label>
											<input id="t_Supplier" type="checkbox" name="option4" value="Supplier"><label class="checkbox" for="t_Supplier">Supplier</label>
											<input id="t_Employee" type="checkbox" name="option5" value="Employee"><label class="checkbox" for="t_Employee">Employee</label>
											<input id="t_Ex employee" type="checkbox" name="option6" value="Ex employee"><label class="checkbox" for="t_Ex employee">Ex employee</label>
											<input id="t_other" type="checkbox" name="option7" value="other"><label class="checkbox" for="other">other</label>
											<br><br><br>
											<div>Describe your relationship to the acquiring corporation</div>
											<input id="Investor" type="checkbox" name="option1" value="Investor"><label class="checkbox" for="Investor">Investor</label>
											<input id="Customer" type="checkbox" name="option2" value="Customer"><label class="checkbox" for="Customer">Customer</label>
											<input id="Partner" type="checkbox" name="option3" value="Partner"><label class="checkbox" for="Partner">Partner</label>
											<input id="Supplier" type="checkbox" name="option4" value="Supplier"><label class="checkbox" for="Supplier">Supplier</label>
											<input id="Employee" type="checkbox" name="option5" value="Employee"><label class="checkbox" for="Employee">Employee</label>
											<input id="Ex employee" type="checkbox" name="option6" value="Ex employee"><label class="checkbox" for="Ex employee">Ex employee</label>
											<input id="other" type="checkbox" name="option7" value="other"><label class="checkbox" for="Other">other</label>
										</div>
										<label class="inner_header">Could you elaborate more about it?  (optional)</label>
										<h4>Synergies  (cost , revenue )</h4>
										<textarea id="new_deal_elaborate"></textarea>
										<h4>Culture match</h4>
										<textarea id="new_deal_elaborate"></textarea>
										<h4>Enhancement of  product brand geography</h4>
										<textarea id="new_deal_elaborate"></textarea>
										<footer>
											<%= submit_tag :search, :name => nil, :class=>"green_back submit", :value=>'Add Insight' %>
										</footer>
									</section>
<% end %>									
									

app/views/deals/_show_content_in_tabs.html.erb
<!-- **************************TABS***************************************************** -->					

	<div id="tabs" class="deal_page">
		<div class="add_container"><a title="Add Insights to this deal" class="gray_back add_butt">Add Insight</a></div>
				 <ul>
					<li><a href="#tabs-1">Deal Insights</a></li>
					<li><a href="#tabs-2">Corporation A info</a></li>
					<li><a href="#tabs-3">Corporation B info</a></li>									
				</ul>
		 <div id="tabs-1" class="tabs_container"> 
		 	<%=render :partial=> "reviews/review", :locals=>{:responses_text=>"Add Response",:responses_type=>"no_responses"}%> <!-- show review content-->
		 	<!--   ************************************* paiging ****************************************************    -->
			<%=render :partial=> "layouts/paiging" %>
		</div>	
		 <div id="tabs-2" class="tabs_container secondary_tab "><!--deals corporation information -->
		 	<article class="tabs_display corp_info">
				<h1>Corporation  title</h1>
				<p>Corporation  info</p>								  			
			</article> 	
		 </div>
		 <div id="tabs-3" class="tabs_container secondary_tab"><!--deals corporation information -->
		 	<article class="tabs_display corp_info">
				<h1>Corporation  title</h1>
				<p>Corporation  info</p>								  			
			</article>
		 </div>
  </div>		 			


							
							

app/views/deals/index.html.erb
				
						<div id="intro"></div>	<!--fix rails bug -->
						<!-- ************************** SEARCH + INNER HEADER***************************************************** -->	    		
						<div id="inner_header_big" class="light_gray_back">
							<h1 id="top_header">Deals</h1>
						 <%=render :partial=> "search/form" , :locals => { :header_name => 'text_inner' } %>	
							<div id="add_top" class="add_deal">
								<div class="circle left gray_back">+</div>
									<a  href="#" class="add_deal">Add a Deal</a>									
							</div>
						</div>	
								
					<div id="main_home" class="deal_nav">
						<!-- ******************************** BREAD CRUMBS **********************************************-->
						<div class="bread_crumbs"><a href="">Home</a> > Deals</div>
						<!-- **************************DEALS FILTERS***************************************************** -->				
							<section class="deals_filter">
									<div class="level2_body"><div class="level2_header deals_fillter">Top Rated</div></div>	
									<table>
										<tr>
											<%=render :partial=> "deals/deal" %>
											<%=render :partial=> "deals/deal" %>
											<%=render :partial=> "deals/deal" %>
										</tr>										
									</table>
								</section>
								<section class="deals_filter">		
									<div class="level2_body"><div class="level2_header deals_fillter">Most Viewed</div></div>
									<table>
										<tr>
											<%=render :partial=> "deals/deal" %>
											<%=render :partial=> "deals/deal" %>
											<%=render :partial=> "deals/deal" %>
										</tr>							
									</table>																
							     </section>
							     <section class="last_filter deals_filter"">		
									<div class="level2_body"><div class="level2_header deals_fillter">Recently Added</div></div>
									<table>
										<tr>
											<%=render :partial=> "deals/deal" %>
											<%=render :partial=> "deals/deal" %>
											<%=render :partial=> "deals/deal" %>
										</tr>							
									</table>																
							     </section>
							      <!-- ************************* ADD DEALS *********************************** -->
								<section id="add_link">
									<div id="add_top" class="add_deal">
										<div class="circle left gray_back">+</div>
										<a  href="#" class="add_deal">Add a Deal</a>									
									</div>
								</section>	
						</div><!-- main home-->

app/views/layouts/_footer.html.erb
<footer class="footer_margin">
		<ul>
			<li class="footer_item"><a href="about.html">About</a></li>
			<li>|</li>
			<li class="footer_item"><a href="contact.html">Contact</a></li>
			<li>|</li>
			<li class="footer_item"><a href="faq.html">FAQ</a></li>
			<li>|</li>
			<li class="footer_item"><a href="learning_center.html">Learning Center</a></li>
			<li>|</li>
			<li class="footer_item"><a href="#">Terms of Service</a></li>
		</ul>
		<div id="rights">All rights reserved MERJERZ &copy 2011</div>	
</footer>										

app/views/layouts/_header.html.erb
<header>
		<div id="logo"><%= link_to logo, root_path %><span class="beta">BETA</span></div>
		<div id="login_area"><a href="#">Login</a> | <a href="#">Sign up</a></div>
</header>

app/views/layouts/_navigation.html.erb
<nav>
	<ul class="green_back">		
				<%= link_to (write_path),:class=>"a_nav" do %>
						<li id="write_nav" class="nav_item">Write</li>							
				<% end %>
				<li>|</li>
				<%= link_to (how_it_works_path),:class=>"a_nav" do %>
						<li id="works_nav" class="nav_item">How it works</li>
				<% end %>
				<li>|</li>
				<%= link_to (corporations_path) do %>
					<li id="corporation_nav" class="nav_item">Corporations</li>
				<% end %>
				<li>|</li>
				<%= link_to (deals_path) do %>
						<li id="deals_nav" class="nav_item">Deals</li>
				<% end %>
				<li>|</li>
				<%= link_to (home_path) do %>
						<li  class="home nav_item"><%=home%></li>
				<% end %>		
				<li>|</li>
			
		</ul>	
</nav>

app/views/layouts/_paiging.html.erb
<div class="paging">
				<table>
					<tr>
						<td class="previous"><a>< Previous</a></td>
						<td class="p_item">1</td>
						<td class="p_item gray_back">2</td>
						<td class="p_item">3</td>
						<td class="next"><a>Next ></a></td>
					</tr>
				</table>
			</div>

app/views/layouts/_search.html.erb
<!--<input id="search_field" type=text class="text_inner"  value="Find information about Corporations and Deals"><input type=submit value="Search" class="submit">-->

<%= form_tag search_path do %>

      <%= search_field_tag :search, params[:search] ,:class="text_home" %>
      <%= submit_tag :search, :name => nil %>
 <% end %>

app/views/layouts/_topSeperator.html.erb
<%= form_tag search_path do %>

      <%= search_field_tag :search, params[:search] ,:class=>header_name, :id=>'search_field'%>
      <%= submit_tag :search, :name => nil, :class=>"submit" %>
     
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= title %> </title>
  <%#= render 'layouts/stylesheets' %>
  <%= stylesheet_link_tag    "application" %>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <%= render 'layouts/header' %>
      <div id="wrapper">
           <%= render 'layouts/navigation' %>
   		 <%= yield %>
   		  <%= render 'layouts/footer' %>
 	 </div><!-- end of wrapper div -->
  
   <%#= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/search/_form.html.erb
<%= form_tag search_path do %>

      <%= search_field_tag :search, params[:search] ,:class=>header_name, :id=>'search_field',:value=>"Find information about Corporations and Deals"%>
      <%= submit_tag :search, :name => nil, :class=>"submit" %>
     
 <% end %>